version: '3.4'

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    container_name: sqlserver
    environment:
        SA_PASSWORD: "Testing123"
        ACCEPT_EULA: "Y"
    ports:
      - "2000:1433"

  jeppesen:
    image: ${DOCKER_REGISTRY-}jeppesen
    container_name: jeppesen
    build:
      context: .
      dockerfile: Jeppesen/Dockerfile
    depends_on: 
      - sqlserver
    healthcheck:
      test: ["CMD", "nmap", "-p", "1433", "sqlserver"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 120s